### ISSUE TITLE
Ribbon buttons not working as expected

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/script-lab#743] opened 2018-01-29 21:29 UTC
This morning I noticed that these four Script Lab ribbon buttons aren't working as expected:

![image](https://user-images.githubusercontent.com/3019529/35535321-04669f5a-04f8-11e8-9618-c2a9e3488156.png)

## Expected Behavior
Each of these four ribbon buttons should open the corresponding resource when clicked (both in Excel desktop and in Excel Online).

## Current Behavior
- When running Script Lab in Excel Desktop (version1802, build 9015.1000), the ribbon buttons for **Tutorial**, **Help**, **Reference Docs**, and **Ask the Community** do nothing when clicked.

- When running Script Lab in Excel Online, the ribbon button for **Reference Docs** launches a blank dialog when clicked. (The **Tutorial**, **Help**, and **Ask the Community** buttons work fine.)

## Steps to Reproduce (for bugs)
Excel Desktop:
1.  Launch Script Lab in Excel Desktop.
2.  Click the **Tutorial** button in the Script Lab tab.
3.  Click the **Help** button in the Script Lab tab.
4. Click the **Reference Docs** button in the Script Lab tab.
5. Click the **Ask the Community** button in the Script Lab tab.

Excel Online:
1.  Launch Script Lab in Excel Online.
2. Click the **Reference Docs** button in the Script Lab tab.

## Your Environment
* Version used:  Desktop -- version 1802, build 9015.1000
* Browser Name and version:  Online - Chrome  version 63.0.3239.132
* Operating System and version (desktop or mobile): Windows desktop

**Comment by Zlatkovsky** [comment] 2018-01-30 01:43
Assigning to Michael Saunders, who had implemented the ribbon buttons and corresponding functions.js.  I wonder if we have a platform regression here, as this definitely used to work.

@saunders77, IIRC, there were a number of other related Ribbon issues.  E.g.,:
https://github.com/OfficeDev/script-lab/issues/395
https://github.com/OfficeDev/script-lab/issues/402

They are somewhat different from this one, but perhaps they can be solved all-up by redesigning the logic (using window.open, for example, and doing different actions on different platforms).

**Comment by cindymeister** [comment] 2018-02-01 18:12
I confirm that I see the same thing in Word (Windows Desktop)

**Comment by kbrandl** [comment] 2018-02-01 18:53
@cindymeister -- here are links to the resources that the buttons should load:

- **Tutorial**: https://github.com/OfficeDev/script-lab/blob/master/src/client/assets/documents/script-lab-tutorial.xlsx

- **Help**: https://github.com/OfficeDev/script-lab/blob/master/README.md

- **Reference Docs**: https://dev.office.com/reference/add-ins/javascript-api-for-office

- **Ask the Community**: https://stackoverflow.com/questions/tagged/office-js

**Comment by cindymeister** [comment] 2018-02-01 19:19
Thank you, Kim. Is there also a tutorial for Word?

**Comment by kbrandl** [comment] 2018-02-01 20:44
I don't believe there's a separate tutorial for Word.  Since Script Lab is a single add-in that can be used within various Office applications (Word, Excel, etc.), the way in which you interact with Script Lab (e.g., Code, Run, Share, etc.) is basically the same regardless of which Office Application you're running Script Lab in. Therefore, even though the tutorial contains Excel screenshots, the same general process should apply to using Script Lab in Word (with the exception of the specifics about the Excel basic snippet, that is).

**Comment by cindymeister** [comment] 2018-02-04 17:33
Hi Kim

 

1.      Since I clicked a link you gave me, rather than using the (non-working) button in the Script-Lab Ribbon tab, I’m not sure what experience the developer starting out in Word was going to/supposed to have. The link opened an Excel workbook. My first reaction was total confusion: “What the dickens am I doing in Excel, I’m starting out in Word? Did I do something wrong?” It took me literally quite a few seconds to realize I hadn’t made a mistake and that I wasn’t expected to actually WORK in Excel. 

 

I think it might help disoriented non-Excel devs if you would extend the Ribbon button description along the lines of: “Launches a quick Script Lab tutorial in Excel.”

 

2.      It also took some time to figure out there are “pages to turn” since the thing is so big (tall) I don’t see the bottom half at any useful % scale – and I’m using a reasonably large monitor.

 

3.      Please note that on the last “page” the last line of text is cut off. I see only “You can share your code snippets as gists directly from Script Lab by signing in to your” until I click on it, then the last line appears.

 

Just passing on my initial reaction, and since this is meant for people just starting out I’d say it’s pretty average for a non-Excel person… ☺

 

               -- Cindy

**Comment by kbrandl** [comment] 2018-02-06 00:04
Thanks for the additional feedback, Cindy. I can certainly appreciate how it'd be disorienting for you to be taken into Excel when you click the **Tutorial** button from within Script Lab in Word. Since Script Lab was built as an experimental learning tool (and is not (yet) an official Microsoft product), it's not surprising that there's some room for improvement in areas like this (Tutorial, Help, etc.).  Thanks for pointing out these things so that we can consider them as we're planning future updates to Script Lab in the days ahead.

**Comment by Zlatkovsky** [comment] 2018-02-08 18:38
Sounds like buttons not launching anything might be a platform issue.  Julian is looking into it.

**Comment by Zlatkovsky** [comment] 2018-02-14 23:09
Looks like it's not a platform issue after all.  Instead, it's an issue with "initialize" not firing, probably a regression on my part as part of some host-initialization refactoring.  Should be simple-ish to fix.

**Comment by letmaik** [comment] 2018-04-02 01:08
Same on PowerPoint Desktop.

**Comment by Zlatkovsky** [comment] 2018-04-26 01:09
Fixed.

**Closed by Zlatkovsky** 2018-04-26 01:09 UTC
Labels: bug, simple, under investigation
