### ISSUE TITLE
The last word of the first line in error messages is broken within the word

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#412] opened 2017-05-07 08:06 UTC
Hi there,

when an error message is displayed and depending on the length of the error message, there are some cases where the last word of the first line is broken within the word. Please see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/13045898/25778867/111c9a5c-330b-11e7-8e97-f25a33abf853.png)

I noticed this while translating Script Lab to German, where some error message are much more longer than in English.

For reproducing, please open Script Lab and e.g. try to import an invalid Gist-URL. When the error message appears, then resize the Code Task Pane so that it is very small in width. Then you can see the word break in an English version of Script Lab.

I played a little bit with the CSS on my fork and I have seen, that if I comment out the line `word-break: break-all;` in `src/client/assets/styles/_fabric.scss` at the following position, then the problem seems to be solved in my local install.
```
    &-subText {
        font-size: 14px;
        font-weight: 400;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        white-space: pre-line;
    /*  word-break: break-all; */
    }
```
However, I don't know, if then other things are affected, but may be it's helpful.

Best,
Mourad

**Comment by Zlatkovsky** [comment] 2017-05-07 17:44
@WrathOfZombies , is the CSS tweak that Mourad proposed below OK, or was there some other reason by which you did word-break: break-all?

FWIW, it looks like what we really want is something slightly different than either value on this property. 
 It instead appears that "overflow-wrap: break-word" is what was intended (to let URLs wrap), but without the harmful side-effect.

http://stackoverflow.com/questions/1795109/what-is-the-difference-between-word-break-break-all-versus-word-wrap-break/

@WrathOfZombies, please weigh in with your opinion.

**Comment by Zlatkovsky** [comment] 2017-05-09 06:50
@WrathOfZombies , fixed with

        word-break: break-word;
        overflow-wrap: break-word;

**Comment by Zlatkovsky** [comment] 2017-05-09 22:27
Deployed & live.

**Closed by Zlatkovsky** 2017-05-09 22:27 UTC
Labels: resolved-awaiting-prod-deployment, simple
