### ISSUE TITLE
Chasing Dots is all I get

### ISSUE THREAD

**Issue by fdncred** [OfficeDev/script-lab#365] opened 2017-04-19 15:05 UTC
With the Script-Lab--a-Microsoft.Garage-project.xlsx or any other excel file, all I get is the code pane with chasing dots. It's like the add-in never initializes.  I can start a new spreadsheet and add Script-Lab through the store button and it does the same thing. I told it I trusted the add-in so I'm not sure what else I need to do to get it running.

Thanks,
Darren

**Comment by Zlatkovsky** [comment] 2017-04-19 15:43
@fdncred , thanks for reporting.  We had one other person report this issue on one of their computers; though he said that he's actually had various IE issues on that computer (and on the desktop, that is what add-ins use for their hosting environment).

Let me investigate and get back to you.  In the meantime, just in terms of getting unblocked, you should be able to try it out online (create a document in OneDrive and insert the add-in there -- just use a different browser, like Edge or Chrome), or try it on another computer.

Will respond soon with some diagnostic steps that if you could run, could help us diagnose the issue.

Thanks!
- Michael

**Comment by Zlatkovsky** [comment] 2017-04-20 05:08
@WrathOfZombies , what I saw based on another person's repro is that there is a script failure somewhere within vendor.bundle.js -- the issue repros even in the normal browser, in that if said person goes to IE and opens up https://script-lab.azureedge.net/, he/she gets the same error even before the host-selection lights up.

Is there an easy way for us to publish vendor.bundle.js in non-minified form, to aid in debugging?  I created a test azure website, but wasn't sure how to de-bundle or at least non-minifiy the vendor file (commenting out the following was *not* enough):

            new webpack.optimize.CommonsChunkPlugin({
                name: ['vendor', 'polyfills'],
                minChunks: Infinity
            })

Thanks!

**Comment by Zlatkovsky** [comment] 2017-04-26 15:09
@WrathOfZombies , ping

**Comment by WrathOfZombies** [comment] 2017-04-26 17:13
@Zlatkovsky you can go ahead and disable the UglifyJsPlugin here: https://github.com/OfficeDev/script-lab/blob/master/config/webpack.prod.js#L45

I'd advice against doing this in prod and asking @fdncred here to sideload the EDGE manifest as the size of the codebase when not optimized is a lot.

**Comment by Zlatkovsky** [comment] 2017-04-26 17:17
@WrathOfZombies, agreed that we shouldn't do this in prod.  My intent was merely to disable in my local dev environment, then publish the debug artifacts to an Azure Website for testing.

The line you're pointing to is in "webpack.prod.js", though.  This shouldn't have impact on a local `npm start` dev build though, right?  Are you able, in your environment, to get a de-bundled and unminified version when you do a local build?

Thanks!

**Comment by WrathOfZombies** [comment] 2017-04-26 20:48
Huh dont see why local should be minified at all. Will get back to you.

**Comment by WrathOfZombies** [comment] 2017-04-28 20:16
**Update:** Seems webpack loads minified files during bundling and I am not sure where this is configured.  That said, because sourcemaps are enabled you can also debug via the sources tab to see the unminified view.

**Comment by ProfessorJimJam** [comment] 2017-05-10 16:54
Hi Michael,
since, you have merged my case #368 to this thread, i will continue here to give you some more details.
i met Sudhi in Amsterdam and i explained the problem i had, he told me it is probably the network firewall that is blocking the library. i checked with our ICT department and they have confirmed that there is no restriction from our network and they referred me back here on github, calling it a known issue.

**Comment by WrathOfZombies** [comment] 2017-05-15 23:32
@ProfessorJimJam @fdncred, in order to debug this further, is it possible for you guys to provide the following:
- A fiddler log of all the calls made when the Add-in is being loaded
- And any console errors and network data obtained by using https://dev.office.com/blogs/attach-debugger-from-the-task-pane

**Comment by Zlatkovsky** [comment] 2017-05-15 23:35
@WrathOfZombies , at least in the one other case that I saw of this, being inside the add-in didn't matter.  The same issue, in IE, was seen even by just loading https://script-lab.azureedge.net/?mode=web.

@ProfessorJimJam , @fdncred , that means that you don't even need to attach a debugger via Visual Studio, you can just look at the logs on the IE F12 tools.

**Comment by ProfessorJimJam** [comment] 2017-05-16 02:12
@Zlatkovsky 

i have used IE F12 Tools and here is the log.

i could open https://script-lab.azureedge.net  then asked me to choose my host. i selected Excel and the following screenshot shows how it loaded. 

![2017-05-16 04_10_06-](https://cloud.githubusercontent.com/assets/6814823/26086865/bce5c00a-39ed-11e7-9ed2-ec29a4c0990b.jpg)

then i clicked on basic API as shown and i run it. then it got stuck and i got the following error in console screenshot is attached below
![2017-05-16 04_06_08-run snippet - internet explorer](https://cloud.githubusercontent.com/assets/6814823/26086895/d99cc4b4-39ed-11e7-8a04-937d3441230e.jpg)

**Comment by WrathOfZombies** [comment] 2017-05-16 03:10
@ProfessorJimJam could you try that scenario again after a couple of hours. I have updated the CORS matrix for our servers and it should be resolved, else we'll need to investigate further.

**Comment by Zlatkovsky** [comment] 2017-05-16 04:28
For what it's worth, when browsing from the website but outside of Office (not Office Online), "run" shouldn't really work in any case.  We just haven't yet disabled the presence of "run" on pure-web for Office snippets yet (https://github.com/OfficeDev/script-lab/issues/225).

My reason for asking to try the browser was that for at least one user, the browser version didn't event get to the host-choice question, and simply hung on the chasing dots.

**Comment by fdncred** [comment] 2017-05-16 16:35
I just now did the same thing ProfessorJimJam did and this is what I got.
![image](https://cloud.githubusercontent.com/assets/343840/26117312/b6324858-3a2b-11e7-92f6-3b77332fade6.png)

**Comment by WrathOfZombies** [comment] 2017-05-16 23:02
@fdncred, in your situation, you are loading `Office.js` as a dependency. For snippets that are run outside the context of an Add-in, this wont work. Go to the libraries tab and remove `office.js` and try again.

@Zlatkovsky I think we need to prioritize fixing this behavior and not from Script Lab but form the platform side of things.

**Comment by Zlatkovsky** [comment] 2017-05-17 00:18
OK, let's separate out the two issues.

**Issue 1, the original one in this thread**:  someone accessing _from within an add-in_ is unable to get the editor to come up.  Definitely a bug, possible on Script Lab or a dependency, though we've yet to identify what exactly is causing it.  For the one case I saw it over screen-sharing, the same issue happened in IE even outside the browser.

**Issue 2, the running snippet**:  there is a Script Lab and a platform aspect to it.  The platform aspect is that there is no `Office.ready` event.  The Script Lab aspect is that we are (intentionally) waiting on `Office.initialize` to fire within the running snippet, and so if run outside of Office, the running snippet fails.  This is the bug #225 -- which I'll prioritize fixing just to avoid the confusion.

**Comment by ProfessorJimJam** [comment] 2017-05-17 13:40
just to  put a quick update,

i run the script again today and the issue presists.

on the web version, i opened https://script-lab.azureedge.net/ and it asked me to choose host and i selected excel and then by running a basic API Chasing Dots is all I get.

**Comment by WrathOfZombies** [comment] 2017-05-17 22:40
@ProfessorJimJam as @Zlatkovsky explained above, this is expected. We can only let you see excel snippets on the web but we can't let you run them as there is no Excel host available.

**Comment by fdncred** [comment] 2017-05-18 18:09
ok, so since I have the issue within Excel, how do I test in order to help you diagnose what the problem is. I have the add-in, I click the script lab tab, I click code, the code window pops out and the chasing dots never go away. Is there some way to debug this where I can help you?

**Comment by fdncred** [comment] 2017-05-18 18:15
I just noticed the Attached Debugger button.  This is what I get when I do that.
![image](https://cloud.githubusercontent.com/assets/343840/26217141/04e1f164-3bcc-11e7-9ef4-1a0d4004bfbc.png)

Unhandled exception at line 1, column 80131 in https://script-lab.azureedge.net/polyfills.bundle.js
0x800a139e - JavaScript runtime error: Office.js has not been fully loaded yet. Please try again later or make sure to add your initialization code on the Office.initialize function. occurred

**Comment by Zlatkovsky** [comment] 2017-05-18 19:09
@fdncred , that error might be a red herring.

Let me ask the same question I did of someone else earlier:  Do you get the same issue if you try to load <https://script-lab.azureedge.net/?mode=web> on Internet Explorer?  Specifically, I am asking about the _editor_ loading, not about the running snippet.

**Comment by fdncred** [comment] 2017-05-18 19:17
@Zlatkovsky Correct. IE gives the same chasing dots. Edge & Chrome come up fine with that URL though.

**Comment by Zlatkovsky** [comment] 2017-05-19 00:44
OK, thanks.  @WrathOfZombies , what does it take for us to debug @fdncred 's case?  @fdncred , could you share a Fiddler log with us? (feel free to email it to me directly if it ends up containing semi-sensitive info: [first name dot last name at company-i-work-for dot com])

**Comment by fdncred** [comment] 2017-05-19 13:11
@Zlatkovsky I can try but I don't see where to download fiddler except for Telerik's paid version.

**Comment by fdncred** [comment] 2017-05-19 13:29
Doh! I already had it installed.  @Zlatkovsky I just emailed you the fiddler log file.

**Comment by ProfessorJimJam** [comment] 2017-06-16 00:51
i am just wondering if there is any update on this issue

**Comment by Zlatkovsky** [comment] 2017-06-16 01:57
We were able to diagnose the issue and believe it's related to browser configuration settings with respect to local storage.  It appears that on some computers, local storage is blocked (at least, when running inside of the add-in, even if it works fine in normal Internet Explorer browsing)

I just created a pull request for the fix here:  https://github.com/OfficeDev/script-lab/pull/450

I will merge it in momentarily, and you'll be able to try it out on the "bleeding edge" build of Script Lab, if you'd like.

It still won't necessarily fix your problem, but at least it will nicely inform you about it :-)

![image](https://user-images.githubusercontent.com/2230453/27208755-643cc0ee-51fc-11e7-94e1-6fca0cc1e088.png)

In terms of a practical workaround:  I'm afraid that until we have someone figure out the platform side of the issue (I sent out an email internally regarding this), your best bet is to use Office Online or try another computer.  Sorry I can't be of more help on this front...

**Comment by Zlatkovsky** [comment] 2017-06-16 02:04
The "bleeding edge" build is ready.

To try this out, please sideload this manifest:  https://github.com/OfficeDev/script-lab/blob/master/manifests/script-lab-edge.xml

Sideloading instructions can be found at:  https://aka.ms/sideload-addins.

You should (theoretically) see the same image as I had above, with an explanation of the local storage issue instead of the chasing dots.

@ProfessorJimJam , if you can confirm whether this is the case for you or not, that would be great!

**Comment by ProfessorJimJam** [comment] 2017-06-21 10:59
Thanks Michael.
I think, i will use my personal machine to work with Script Lap. 

the sideloading option did not work for me, as i could not share the folder with myself.
![ss](https://user-images.githubusercontent.com/6814823/27380875-1495e672-5681-11e7-9b8f-a2713c4efc71.jpg)

on the setting, i checked the local storage "Enable DOM Storage" was enabled and i also tried also unmarking the Disable Script Debugging  and then when loaded. i got the following errors
Line: 1
Error: Access is denied.
Line: 1
Error: Office.js has not been fully loaded yet. Please try again later or make sure to add your initialization code on the Office.initialize function.

Line: 109
Error: Unable to get property 'indexOf' of undefined or null reference
![2017-06-21 12_44_49-](https://user-images.githubusercontent.com/6814823/27380972-5e7e8956-5681-11e7-8559-74c70de683b0.jpg)

**Closed** 2017-08-06 16:10 UTC
Labels: blocker, resolved-awaiting-prod-deployment, resolved-awaiting-validation
