### ISSUE TITLE
Unexpected error when deactivating Firebug

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#375] opened 2017-04-25 16:21 UTC
Hi there,

I searched, if something similar has already been posted here, but could not find a topic. I hope, I did not oversee something. When deactivating Firebug, I get an unexpected error from the Add-In. Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13045898/25394154/c1da9434-29dd-11e7-921c-8d11882f2a17.png)

Also, when clicking then on "Load the last snippet", nothing happens (or may be, the error is reloaded). The other buttons work. For reproducing, please follow these steps...

- Open the task panes for Code and Run from the Script Lab ribbon.
- Create a new blank snippet.
- Run the blank snippet.
- Please click on 'Deactivate Firebug for this page'.
- Change something in the code window, e.g. just add a line.
- The runner task pane asks you to refresh.
- Please refresh and the error appears.

Sometimes, after going back to the page with the list of snippets for running the last snippet again and repeating the steps for producing the error page, the error page did not show the "Back" button. However I could not reproduce this constantly.

My current version of Script Lab is 1.1.0 (Deployed 2017-04-16 21:53 pm UTC) and my User ID is cj1taawts0000586wmychyiyx.

Best,
Mourad

**Comment by Zlatkovsky** [comment] 2017-04-26 15:05
Thanks for the detailed report!  I will try it out later this week.  Just to be sure, based on the screenshots,  this is on a Windows build of Office, correct?

**Comment by maninweb** [comment] 2017-04-26 15:45
Hi, yes - I had the error in Excel 2016 Version 1704 Build 8067.2018 on a Windows 10 and Windows 7 OS.

**Comment by Zlatkovsky** [comment] 2017-04-26 15:55
OK, perfect, thanks for the clarification.  Will take a look in the coming days.

Just to check:  if you re-open the panes, does Firebug come back?  Or are you essentially in a blocked / broken state now, and cannot proceed to use Script Lab?  This will also help gage the severity of this issue.

**Comment by maninweb** [comment] 2017-04-26 16:24
If I get the error and go back to the list of scripts inside the Run Task Pane by clicking on the arrow (left) and then call the script again, Firebug automatically reappears. If I close the Task Pane and reopen it from the ribbon, I get automatically see this list of scripts and Firebug also appears again. When having the Run Task Pane open with the error inside and then clicking in the ribbon on Run, nothing happens.
Even if the Run Task Pane shows the error, I can continue to edit in the Code Task Pane. So, no issues there. However, on code changes, it synchronizes with the Run Task Pane and asks me to refresh. If the error was still in the Run Task Pane, then on this refresh, the error appears again. So, I have ensure that Firebug is active, meaning not to deactivate it.

**Comment by Zlatkovsky** [comment] 2017-04-26 17:11
OK, I can reproduce the issue. It looks like it's happening because a reload is trying to write to a console created by a disposed Firebug instance, and is failing.

Simplest fix is to remove the ability to dispose Firebug, and instead leave only the "minimize" button.  Will do this now.  The effect is similar, except that instead of being fully 100% hidden, there is a 40px bar at the bottom with the Firebug logo.  That still seems like a marked improvement over today's experience.

I will close this issue once the fix makes it to prod.  By "this issue" I mean precisely the error you are getting.

If this bug report is also a larger discussion about the console (e.g., you'd like to have an option to always auto-hide the console until something is written to it; or to never show it at all; or have a toggle for it somewhere in the header; or etc etc) please open a separate issue for that.

Thanks!

**Comment by maninweb** [comment] 2017-04-26 18:17
Thanks :-)

**Comment by Zlatkovsky** [comment] 2017-04-27 02:10
Fix is done, and is in production already.  Thanks for reporting!

**Closed by Zlatkovsky** 2017-04-27 02:10 UTC
Labels: bug
