### ISSUE TITLE
Use browser instead of the modal to open

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/script-lab#436] opened 2017-05-30 22:34 UTC
Right now on macOS, when I clicked `Reference Docs` or `Ask the Community`, it opens a modal.
I have to close the modal to continue using Excel.
Maybe we should just use the browser to open it.

![image](https://cloud.githubusercontent.com/assets/3375461/26607777/0ac7af08-454d-11e7-9fef-8ae0ac379c33.png)

**Comment by jakobpn** [comment] 2017-05-30 22:45
And there are no scroll bars which makes in impossible to read the content of the page.

**Comment by Hongbo-Miao** [comment] 2017-05-30 22:56
Yeah, the mouse scroll and touchpad does not work on this page.

**Comment by Zlatkovsky** [comment] 2017-05-30 23:34
Duplicate of https://github.com/OfficeDev/script-lab/issues/402.
But, @saunders77 , still (doubly) worth doing...

**Closed** 2017-05-30 23:34 UTC
