### ISSUE TITLE
Trust a snippet message on first run of the code pane

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#816] opened 2018-05-20 09:00 UTC
Hi there,

I created a fresh virtual machine with Windows 10 and installed Excel Insider (10211.20004) by using the Office Deployement toolkit. Once all things installed, I installed Script Lab 1.1.0 from the **store**. On its first run, the code pane shows me the samples. That's ok.

![image](https://user-images.githubusercontent.com/13045898/40277019-27c3c3d4-5c18-11e8-8121-62d503131482.png)

Without creating any script from a sample or a new one, if I then click on the Hamburger menue, I get a message to trust the script from the external source, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/13045898/40277042-892b9a52-5c18-11e8-867f-caa93ff4ea45.png)

However, I can not click on the button Trust (Vertrauen) and therefore not dismiss the message. But it is possible to reach the trust button by clicking somewhere in the green header (not the buttons) of the code pane and then pressing the tab key. Nothing happens then when pressing the trust button with the space key. If I press the tab key again, I reach the editor in the background and I can write something there.

![image](https://user-images.githubusercontent.com/13045898/40277071-3db02b46-5c19-11e8-87c0-f16bdc78cb32.png)

I hope, I have not overseen an already posted issue here.

Best,
Mourad

**Comment by nico-bellante** [comment] 2018-05-21 21:52
Pretty sure the root cause of this issue is due to the fact that [here](https://github.com/OfficeDev/script-lab/blob/master/src/client/app/containers/editor.ts#L82) isSnippetTrusted defaults to false, which is the flag that is used to show the trust bar, and in the example above, there is no snippet to trust. Should be an easy fix.

**Comment by nico-bellante** [comment] 2018-05-22 20:36
Fixed in PR #821

**Comment by Zlatkovsky** [comment] 2018-05-22 22:35
@maninweb , FYI, for any of these fixes, we first put them into the "Alpha" environment, and eventually promote them to Beta/Prod.
You can switch to Alpha as follows:  https://github.com/OfficeDev/script-lab/blob/master/.github/images/switch-to-alpha.png

**Closed** 2018-05-22 22:35 UTC
Labels: bug, resolved-awaiting-prod-deployment, simple
